openapi: 3.0.0
info:
  title: By Bicycle Delivery
  description: >-
    An advanced microservice transforming last-mile logistics. It offers
    seamless ordering features, including quotation and booking.
  version: 1.0.0
servers:
  - url: http://localhost:80
    description: Development
tags:
  - name: Orders
    description: |-
      **Getting Started**

      1. Request a quote to initiate the process.
      2. Review the quote to get the shipment cost.
      3. Confirm your booking by using the provided quote ID.
      4. Keep track of your order status using the assigned order ID.
paths:
  /orders/quote:
    post:
      tags:
        - Orders
      summary: Request Quote
      description: >-
        This endpoint allows you to create a new quote for an order.


        Distance range between shipper and destination is 3-300KM


        ## Request Body


        | **Field** | **Type** | **Constraints** |

        | --- | --- | --- |

        | shipper.address.shipperCountry | string (length: 2) | Allowed values:
        'DE', 'DK', 'PL', 'CZ', 'AT', 'CH', 'FR', 'BE', 'NL' |

        | shipper.address.shipperCity | string |  |

        | shipper.address.shipperPostcode | string |  |

        | shipper.shipperPickupOn | string (datetime) | Format:
        'YYYY-MM-DDTHH:00:00Z'. Pickup date must be in the future. Only whole
        hours allowed.  <br>  <br>Orders placed after 10:30 must be booked for
        next day or later.  <br>  <br>Pickup time is from when we can come to
        pickup and not exactly when we will pickup |

        | consignee.address.consigneeCountry | string (length: 2) | Allowed
        values: 'DE', 'DK', 'PL', 'CZ', 'AT', 'CH', 'FR', 'BE', 'NL' |

        | consignee.address.consigneeCity | string |  |

        | consignee.address.consigneePostcode | string |  |

        | consignee.consigneeDeliveryOn | Date | Format: 'YYYY-MM-DD'. Must be
        at least 2 days after pickup and at most 7 days after pickup. No
        weekends allowed. |
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                shipper:
                  address:
                    shipperCountry: DE
                    shipperCity: Berlin
                    shipperPostcode: '10115'
                  shipperPickupOn: '2024-01-15T12:00:00Z'
                consignee:
                  address:
                    consigneeCountry: PL
                    consigneeCity: Słupsk
                    consigneePostcode: 76-200
                  consigneeDeliveryOn: '2024-01-18'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
          content:
            application/json:
              schema:
                type: object
              example:
                message: >-
                  We have received your request. Quote will be available once
                  processed, you can check the status using the quote id.
                quoteId: 3667b1dd-d24a-4ca2-bbc1-7f6e8836e7dd
        '400':
          description: Bad Request
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
          content:
            application/json:
              schema:
                type: object
              example:
                errors:
                  - path:
                      - consignee
                      - consigneeDeliveryOn
                    message: >-
                      At least 2 days are required between expected pickup and
                      delivery.
                  - path:
                      - shipper
                      - shipperPickupOn
                    message: >-
                      Format must be YYYY-MM-DDTHH:00:00Z and date must be in
                      the future.
  /orders/quote/{quoteId}:
    get:
      tags:
        - Orders
      summary: Get Quote
      description: >-
        This endpoint retrieves the details of a specific order quotation
        identified by the provided quoteId.


        The response will include information such as the quoteId, shipper
        details, consignee details, pickup and delivery dates, distance,
        price(CENTS), and status of the quotation. The status could indicate
        that the quotation is being processed and to check back later, or it
        could provide the estimated completion time and the pending status.
        Additionally, the status "QUOTED" may be returned along with the
        price(CENTS) and distance information.


        Please note that the response may vary based on the current status of
        the quotation.
      parameters:
        - name: quoteId
          in: path
          schema:
            type: string
            format: uuid
          required: true
          description: UUID
          example: f8ca95b7-1a14-4edc-b114-f80dfb727cbb
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: Pending Quotation
                  value:
                    message: Quotation is being processed, please check back later.
                    quoteId: f8ca95b7-1a14-4edc-b114-f80dfb727cbb
                    estimatedCompletionTime: 1705224556537
                    status: PENDING
                example-1:
                  summary: Successful Quotation
                  value:
                    quoteId: 3667b1dd-d24a-4ca2-bbc1-7f6e8836e7dd
                    shipper:
                      shipperCountry: DE
                      shipperCity: Potsdam
                      shipperPostcode: '10115'
                    consignee:
                      consigneeCountry: PL
                      consigneeCity: Słupsk
                      consigneePostcode: 76-200
                    shipperPickupOn: '2024-01-09T12:00:00.000Z'
                    consigneeDeliverOn: '2024-01-13T00:00:00.000Z'
                    distance: 50
                    price: 9000
                    status: QUOTED
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
              example:
                message: Invalid quote id
                error: Bad Request
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
              example:
                message: No active quotation found
                error: Not Found
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
              example:
                note: >-
                  The distance between the shipper and consignee is not in
                  operational range.
                distance: 388
                code: 422
                status: Contact us for more information
  /orders/{quoteId}:
    post:
      tags:
        - Orders
      summary: Book Quote
      description: >-
        ### Book Order


        This endpoint allows the user to create an order for a given quote.


        #### Request Body


        - `shipperPickupOn` (Datetime/Timestamp): The date and time for the
        shipper's pickup.

        - `consigneeDeliveryOn` (Date): The date for the consignee's delivery.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                shipper:
                  shipperPickupOn: '2024-01-18T12:00:00Z'
                consignee:
                  consigneeDeliveryOn: '2024-01-21'
      parameters:
        - name: quoteId
          in: path
          schema:
            type: string
            format: uuid
          required: true
          example: f2deb6c6-79d5-4b06-a55b-e157f1a3c7fc
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: Success
                  value:
                    message: Booking successful.
                    orderId: 3
                    quoteId: 3667b1dd-d24a-4ca2-bbc1-7f6e8836e7dd
                    status: BOOKED
        '422':
          description: Unprocessable Entity
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
          content:
            application/json:
              schema:
                type: object
              example:
                message: Invalid quote id
                error: Bad Request
  /orders/{orderId}:
    get:
      tags:
        - Orders
      summary: Retrieve Order
      description: >-
        This endpoint retrieves the details of a specific order identified by
        the orderId parameter. The response contains information about the
        shipper, consignee, pickup and delivery dates, distance, price (CENTS),
        quote ID, and status of the order.
      parameters:
        - name: orderId
          in: path
          schema:
            type: integer
          required: true
          example: '13'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
          content:
            application/json:
              schema:
                type: object
              example:
                shipper:
                  shipperCountry: DE
                  shipperCity: Berlin
                  shipperPostcode: '10115'
                consignee:
                  consigneeCountry: PL
                  consigneeCity: Słupsk
                  consigneePostcode: 76-200
                shipperPickupOn: '2024-01-09T12:00:00.000Z'
                consigneeDeliverOn: '2024-01-13T00:00:00.000Z'
                distance: 50
                price: 9000
                quoteId: 3667b1dd-d24a-4ca2-bbc1-7f6e8836e7dd
                status: BOOKED
        '404':
          description: Not Found
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
        '422':
          description: Unprocessable Entity
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
          content:
            application/json:
              schema:
                type: object
              example:
                message: Invalid order id
                error: Bad Request
