version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_DB: your_postgres_db
      POSTGRES_PASSWORD: your_postgres_password

  redis:
    image: redis
    ports:
      - "6379:6379"
