version: '3.8'

services:
  backend:
    build: .
    ports:
      - '8000:5000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
    container_name: redis
    volumes:
      - data:/data/cache
    ports:
      - 6379:6379

volumes:
  data:
